# Generated by Django 4.0.2 on 2022-02-05 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedimage',
            name='edit_image',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
    ]
