# Generated by Django 4.0.2 on 2022-02-05 09:01

from django.db import migrations, models
import image_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('image_app', '0002_uploadedimage_edit_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadedimage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=image_app.models.get_image_path),
        ),
    ]
