# Generated by Django 4.0.2 on 2022-02-06 06:29

from django.db import migrations, models
import image_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('image_app', '0003_alter_uploadedimage_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadedimage',
            name='edit_image',
            field=models.ImageField(blank=True, null=True, upload_to=image_app.models.get_image_path),
        ),
    ]
