# Generated by Django 4.0.2 on 2022-02-11 07:43

from django.db import migrations, models
import image_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('image_app', '0005_alter_uploadedimage_edit_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedimage',
            name='product_im',
            field=models.ImageField(blank=True, null=True, upload_to=image_app.models.get_image_path),
        ),
    ]
